SistemaGestionClinica/urls.py
from django.urls import re_path, path, include
from django.contrib import admin

#from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include('usuarios.urls', namespace='usuarios')),
    re_path(r'^', include('pacientes.urls', namespace='pacientes')),
    re_path(r'^', include('historiasClinicas.urls', namespace='historias_clinicas')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SistemaGestionOdontologica/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('usuarios.urls', namespace='usuarios')),
    url(r'^', include('pacientes.urls', namespace='pacientes')),
    url(r'^', include('historiasClinicas.urls', namespace='historias_clinicas')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

historiasClinicas/urls.py
#from django.conf.urls import url
from django.urls import re_path
from .views import historia_paciente, HistoriaClinicaListView, ActualizacionCreateView, report, ActualizacionDetailView

app_name = 'historias_clinicas'

urlpatterns = [
    re_path(r'^historia-clinica$', HistoriaClinicaListView.as_view(), name='listar_historias'),
    re_path(r'^historia-clinica/(?P<pk>\d+)$', historia_paciente, name='historia_paciente'),
    re_path(r'^historia-clinica/(?P<pk>[0-9]+)/(?P<pk_A>[0-9]+)$',ActualizacionDetailView.as_view(), name='detalle_actualizacion'),
    re_path(r'^historia-clinica/(?P<pk>[0-9]+)/(?P<pk_A>[0-9]+)/pdf$',report, name='reporte_pdf'),
    re_path(r'^historia-clinica/(?P<pk>[0-9]+)/nueva-entrada$',
        ActualizacionCreateView.as_view(), name='crear_actualizacion'),
]

pacientes/urls.py
#from django.conf.urls import url
from django.urls import re_path
from .views import CrearPaciente, DetallePaciente, PacienteListView
from django.views.decorators.csrf import csrf_exempt

app_name = 'pacientes'

urlpatterns = [
	re_path(r'^pacientes/nuevo', csrf_exempt(CrearPaciente.as_view()), name='nuevo_paciente'),
    re_path(r'^pacientes$', PacienteListView.as_view(), name='listar_pacientes'),
    re_path(r'^pacientes/(?P<pk>\d+)$', DetallePaciente.as_view(), name='detalle_paciente'),
]

usuarios/urls.py
#from django.conf.urls import url
from django.urls import re_path
from . import views

app_name = 'usuarios'
urlpatterns = [
    re_path(r'^$', views.autenticar, name = 'autenticar'),
    re_path(r'^logout$', views.desautenticar, name = 'desautenticar'),
    re_path(r'^inicio$', views.inicio, name = 'inicio'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		{% load staticfiles %}
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/base.css' %}">
		
		{% block style_content %}
			
		{% endblock style_content %}
	</head>
	<body>
		<header id="header-container">
			<div class="container-fluid">
				<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
					<a class="navbar-brand" href="/inicio">Gestion medica</a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
					</button>
					<div class="collapse navbar-collapse justify-content-between" id="navbarNavDropdown">
						<ul class="navbar-nav">
							<li class="nav-item {{active_inicio}}">
								<a class="nav-link" href="/inicio">Inicio <span class="sr-only">(current)</span></a>
							</li>
							<li class="nav-item {{active_pacientes}}">
								<a class="nav-link" href="{% url 'pacientes:listar_pacientes' %}">Pacientes</a>
							</li>
							<li class="nav-item {{active_historias}}">
								<a class="nav-link" href="{% url 'historias_clinicas:listar_historias' %}">Historias clinicas</a>
							</li>
							<li class="nav-item {{active_citas}}">
								<a class="nav-link" href="#" data-toggle="modal" data-target="#exampleModal"> Citas </a>
							</li>
						</ul>
						<ul class="navbar-nav">
							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">{{user.first_name}} {{user.last_name}}</a>
								<div class="dropdown-menu">
									<a class="dropdown-item" href="/logout">Logout</a>
								</div>
							</li>
						</ul>
					</div>
				</nav>
			</div>
			<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
				<div class="modal-dialog" role="document">
					<div class="modal-content">
						<div class="modal-header">
							<h5 class="modal-title" id="exampleModalLabel">Lo sentimos!</h5>
							<button type="button" class="close" data-dismiss="modal" aria-label="Close">
								<span aria-hidden="true">&times;</span>
							</button>
						</div>
						<div class="modal-body">
							<p>Esta seccion se encuentra todavia en desarrollo</p>
						</div>
					</div>
				</div>
			</div>
		</header>
		{% block content %}
			
		{% endblock content %}
		<script src="{% static 'js/jquery-3.2.1.min.js'%}"></script>
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
		<script src = "{% static 'js/bootstrap.min.js' %}"></script>
		{% block scripts %}
		
		{% endblock scripts%}
	</body>
</html>

templates/inicio.html
{% extends "base.html" %}
{% load staticfiles %}

{% block style_content %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/inicio.css' %}">
{% endblock style_content %}

{% block content %}
	<section class="section-container">
		<div class="container inicio-container">
			<div class="row">
				<div class="col-12 ">
					<h2 class="text-center">Bienvenido {{user.first_name}} {{user.last_name}}, ¿que desea hacer?</h2>
				</div>
			</div>
		</div>
	</section>

	<section class="section-container">
		<div class="container inicio-container">
			<div class="row justify-content-center">
				<div class="col-12 col-md-6 col-btn">
					<div class="btn-group-vertical btn-group-lg" role="group">
						<a class="btn btn-outline-primary btn-block" href="{% url 'pacientes:nuevo_paciente' %}">Registrar nuevo paciente</a>
						<a class="btn btn-outline-primary btn-block" href="{% url 'pacientes:listar_pacientes' %}">Buscar paciente</a>
						<a class="btn btn-outline-primary btn-block" href="{% url 'historias_clinicas:listar_historias' %}">Buscar historia clinica</a>
						<a class="btn btn-outline-primary btn-block" href="#" data-toggle="modal" data-target="#exampleModal">Citas del dia</a>
						<a class="btn btn-outline-primary btn-block" href="#" data-toggle="modal" data-target="#exampleModal">Agendar cita</a>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock content %}

templates/login.html
<!DOCTYPE html>
<html lang="es">
	<head>
		{% load staticfiles %}
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/login.css' %}">

		<title>Login</title>
	</head>
	<body>
		<section id="section-container">
			<div class="container">
				<div class="row justify-content-center">
					<div class="col-12 col-md-6 col-login">
						<h4>Sistema de gestión medica</h4><br>
						<form method="POST">
							{% csrf_token %}
							<div class="form-group">
								<label for="inputUsuario">Usuario:</label>
								<input type="text" name="inputUsuario" id="inputUsuario" class="form-control" placeholder="Ingrese su usuario">
							</div>
							<div class="form-group">
								<label for="inputContrasena">Contraseña:</label>
								<input type="password" name="inputContrasena" id="inputContrasena" class="form-control" placeholder="Ingrese la Contraseña:">
							</div>
							<button type="submit" class="btn btn-outline-primary btn-block">Ingresar</button>
						</form>
					</div>
				</div>
			</div>
		</section>
		<!-- Optional JavaScript -->
		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		{% load staticfiles %}
		<script src="{% static 'js/jquery-3.2.1.min.js'%}"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
		<script src = "{% static 'js/bootstrap.min.js' %}"></script>
	</body>
</html>