SistemaGestionClinica/urls.py
from django.urls import re_path, path, include
from django.contrib import admin

#from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include('usuarios.urls', namespace='usuarios')),
    re_path(r'^', include('pacientes.urls', namespace='pacientes')),
    re_path(r'^', include('historiasClinicas.urls', namespace='historias_clinicas')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SistemaGestionOdontologica/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('usuarios.urls', namespace='usuarios')),
    url(r'^', include('pacientes.urls', namespace='pacientes')),
    url(r'^', include('historiasClinicas.urls', namespace='historias_clinicas')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

historiasClinicas/urls.py
#from django.conf.urls import url
from django.urls import re_path
from .views import historia_paciente, HistoriaClinicaListView, ActualizacionCreateView, report, ActualizacionDetailView

app_name = 'historias_clinicas'

urlpatterns = [
    re_path(r'^historia-clinica$', HistoriaClinicaListView.as_view(), name='listar_historias'),
    re_path(r'^historia-clinica/(?P<pk>\d+)$', historia_paciente, name='historia_paciente'),
    re_path(r'^historia-clinica/(?P<pk>[0-9]+)/(?P<pk_A>[0-9]+)$',ActualizacionDetailView.as_view(), name='detalle_actualizacion'),
    re_path(r'^historia-clinica/(?P<pk>[0-9]+)/(?P<pk_A>[0-9]+)/pdf$',report, name='reporte_pdf'),
    re_path(r'^historia-clinica/(?P<pk>[0-9]+)/nueva-entrada$',
        ActualizacionCreateView.as_view(), name='crear_actualizacion'),
]

pacientes/urls.py
#from django.conf.urls import url
from django.urls import re_path
from .views import CrearPaciente, DetallePaciente, PacienteListView
from django.views.decorators.csrf import csrf_exempt

app_name = 'pacientes'

urlpatterns = [
	re_path(r'^pacientes/nuevo', csrf_exempt(CrearPaciente.as_view()), name='nuevo_paciente'),
    re_path(r'^pacientes$', PacienteListView.as_view(), name='listar_pacientes'),
    re_path(r'^pacientes/(?P<pk>\d+)$', DetallePaciente.as_view(), name='detalle_paciente'),
]

usuarios/urls.py
#from django.conf.urls import url
from django.urls import re_path
from . import views

app_name = 'usuarios'
urlpatterns = [
    re_path(r'^$', views.autenticar, name = 'autenticar'),
    re_path(r'^logout$', views.desautenticar, name = 'desautenticar'),
    re_path(r'^inicio$', views.inicio, name = 'inicio'),
]

pacientes/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.urls import reverse

# Create your models here.


class Paciente(models.Model):
    estados_civiles = (
        ('soltero', 'Soltero/a'),
        ('casado', 'Casado/a'),
        ('union libre', 'Union libre'),
        ('viudo', 'Viudo/a'),
        ('divorciado', 'Divorciado/a'),
        ('comprometido', 'Comprometido/a')
    )
    sexos = (
        ('masculino', 'Masculino'),
        ('femenino', 'Femenino'),
        ('otro', 'Otro')
    )

    cedula = models.CharField(primary_key=True, max_length=11)
    primer_nombre = models.CharField(max_length=15)
    segundo_nombre = models.CharField(max_length=15, blank=True)
    primer_apellido = models.CharField(max_length=15)
    segundo_apellido = models.CharField(max_length=15)
    direccion = models.CharField(max_length=100)
    ciudad = models.CharField(max_length=50)
    fecha_nacimiento = models.DateField()
    estado_civil = models.CharField(max_length=50, choices=estados_civiles)
    telefono = models.CharField(max_length=10)
    sexo = models.CharField(max_length=15, choices=sexos, default='sexo')
    foto = models.ImageField()


    def __str__(self):
        return self.cedula

    def get_absolute_url(self):
        return reverse('pacientes:detalle_paciente', kwargs={"pk": self.cedula})
 

pacientes/forms.py
from django.forms import ModelForm
from .models import Paciente
from django import forms


class PacienteForm(ModelForm):
    """Form definition for paciente."""

    class Meta:
        """Meta definition for pacienteform."""
        model = Paciente
        fields = '__all__'
        widgets = {'fecha_nacimiento': forms.DateInput(attrs={'class': 'datepicker'})}

pacientes/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from .models import Paciente
from .forms import PacienteForm
from django.http.response import HttpResponse

# Create your views here.


class CrearPaciente(CreateView):
    model = Paciente
    #form_class = PacienteForm
    #template_name = 'pacientes/paciente_form.html'
    fields = [
        'cedula',
        'primer_nombre',
        'segundo_nombre',
        'primer_apellido',
        'segundo_apellido',
        'direccion',
        'ciudad',
        'fecha_nacimiento',
        'estado_civil',
        'telefono',
        'sexo',
    ]

    def post(self, request, *args, **kwargs):
        form = PacienteForm(request.POST, request.FILES)
        if form.is_valid():
            print(request.FILES)
            form.save()
            return HttpResponse('Formulario valido')
        print('no es valido')
        print(request.FILES)
        return HttpResponse('Formulario no valido')

class DetallePaciente(DetailView):
    model = Paciente


class PacienteListView(ListView):
    model = Paciente

templates/pacientes/paciente_detail.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block style_content %}
<link rel="stylesheet" href="{% static 'css/PacienteDetail.css' %}">
<link rel="stylesheet" href="{% static 'css/PacienteRegistro.css' %}">
{% endblock style_content %}



{% block content %}
    <section id="section-container">
        <div class="container">
            <div class="row fila">
                <div class="col-12 col-md-4">
                    <img src="{{ paciente.foto.url }}" alt="Responsive image" class="img-thumbnail">
                </div>
                <div class="col-12 col-md-6 column">
                    <h3>Paciente:</h3>
                    <h2>{{paciente.primer_nombre}} {{paciente.segundo_nombre}} {{paciente.primer_apellido}} {{paciente.segundo_apellido}}</h2><br>
                    <h3>Cedula:</h3>
                    <h2>{{ paciente.cedula }}</h2>
                </div>
            </div>
            <div class="row fila ">
                <div class="col-12 col-md-6 col-lg-4 colDatos">
                    <h5>Ciudad:</h5>
                    <h6>{{ paciente.ciudad }}</h6>
                </div>
                <div class="col-12 col-md-6 col-lg-4 colDatos">
                    <h5>direccion: </h5>
                    <h6>{{ paciente.direccion }}</h6>
                    
                </div>
                <div class="col-12 col-md-6 col-lg-4 colDatos">
                    <h5>Telefono: </h5>
                    <h6>{{ paciente.telefono }}</h6>
                </div>
                <div class="col-12 col-md-6 col-lg-4 colDatos">
                    <h5>Fecha de nacimiento: </h5>
                    <h6>{{ paciente.fecha_nacimiento }}</h6>
                </div>
                <div class="col-12 col-md-6 col-lg-4 colDatos">
                    <h5>Edad: </h5>
                    <h6>{{ paciente.fecha_nacimiento|timesince }}</h6>
                </div>
                <div class="col-12 col-md-6 col-lg-4 colDatos">
                    <h5>Estado civil:</h5>
                    <h6>{{ paciente.estado_civil }}</h6>
                </div>
                <div class="col-12 colDatos">
                    <a href="{% url  'historias_clinicas:historia_paciente' pk=paciente.cedula%}" class="btn btn-outline-primary btn-block">Historia Clinica</a>
                </div>
            </div>
        </div>
    </section>

{% endblock content %}

templates/pacientes/paciente_form.html
{% extends 'base.html' %}
{% load widget_tweaks%}
{% load staticfiles %}

{% block style_content %}
<link rel="stylesheet" href=" {% static 'css/PacienteRegistro.css' %}">
{% endblock style_content %}

{% block content %}
<section id="section-container">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-md-8 col-lg-6 column">
                <h2 class="text-center">Registro Paciente</h2>
            </div>
        </div>
</section>
<section id="section-container">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-md-8 col-lg-6 column">
                <form method="POST" id="form-paciente">
                    {% csrf_token %}
                    {% for hidden in form.hidden_fields%}
                    {{hidden}}
                    {% endfor %}
                    {% for field in form.visible_fields %}
                    <div class="form-group">
                        <label for="{{field.id_for_label}}">{{field.label}}</label>
                        {{ field|add_class:'form-control'}}
                        {% if field.name == 'fecha_nacimiento' %}
                        <small id="date-help" class="form-text text-muted">Porfavor use el siguente formato 'YYYY-MM-DD'</small>
                        {% endif %}
                    </div>
                    {% endfor %}
                    <div class="form-group">
                            <p>Foto</p>
                            <div class="row mb-5">
                                <div class="col-6 pl-5">
                                    <p><strong id="label-picture">La foto no ha sido tomada</strong></p>
                                </div>
                                <div class="col-6 d-flex justify-content-end">
                                    <!-- Button trigger modal -->
                                    <button id="webcam-modal-button" type="button" class="btn btn-primary" data-toggle="modal"
                                        data-target="#webcam-modal">
                                        Tomar foto
                                    </button>
                                </div>
                            </div>
                    </div>
                    <!-- <input type="submit" class="btn btn-outline-primary btn-block"> -->
                    <div id="submit" class="btn btn-outline-primary btn-block">Guardar</div>
                </form>

                <!-- Modal webcam-->
                <div class="modal fade" id="webcam-modal" tabindex="-1" role="dialog" aria-labelledby="WebcamModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog modal-lg" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="WebcamModalLabel">Toma la foto del paciente</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <div class="container-fluid">
                                    <div class="row">
                                        <div class="col-12 d-flex justify-content-center">
                                            <video id="video"></video>
                                        </div>
                                        <div class="col-12 d-flex justify-content-center">
                                            <canvas id="canvas"></canvas>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                                <button id="take-picture-button" type="button" class="btn btn-primary">Tomar foto</button>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Modal Ajax done-->
                <div class="modal fade" id="ajax-modal" tabindex="-1" role="dialog" aria-labelledby="ajax-modal"
                    aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="ajax-modal">Paciente guardado</h5>
                                <button type="button" class="close" data-dismiss="ajax-modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <p>Los datos del paciente han sido guardados correctamente, sera redirigido a la lista
                                    de pacientes en 3 segundos</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

{% block scripts%}
<script src="{% static 'js/camara.js' %}"></script>
<script src="{% static 'js/postNuevoPaciente.js' %}"></script>
{% endblock scripts %}

templates/pacientes/paciente_list.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block style_content %}
    <link rel="stylesheet" href="{% static 'css/PacientesLista.css' %}">
    <link rel="stylesheet" href="{% static 'css/PacienteRegistro.css' %}">
{% endblock style_content %}

{% block content %}
    <section id="section-container">
        <div class="container">
            <div class="row fila">
                <div class="col-12 text-center pt-3 pb-2">
                    <h2>Lista de Pacientes</h2>
                </div>
            </div>
            <div class="row fila">
                <div class="col-12">
                    <div class="list-group">
                        {% for paciente in  object_list%}
                            <a href="{% url 'pacientes:detalle_paciente' pk=paciente.cedula %}" class="list-group-item list-group-item-action flex-column">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="mb-1">{{ paciente.primer_nombre }} {{ paciente.segundo_nombre }} {{ paciente.primer_apellido }} {{ paciente.segundo_apellido }}</h5>
                                    <h5>cedula: {{ paciente.cedula }}</h5>
                                </div>
                            </a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}
    