SistemaGestionClinica/urls.py
from django.urls import re_path, path, include
from django.contrib import admin

#from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include('usuarios.urls', namespace='usuarios')),
    re_path(r'^', include('pacientes.urls', namespace='pacientes')),
    re_path(r'^', include('historiasClinicas.urls', namespace='historias_clinicas')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SistemaGestionOdontologica/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('usuarios.urls', namespace='usuarios')),
    url(r'^', include('pacientes.urls', namespace='pacientes')),
    url(r'^', include('historiasClinicas.urls', namespace='historias_clinicas')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

historiasClinicas/urls.py
#from django.conf.urls import url
from django.urls import re_path
from .views import historia_paciente, HistoriaClinicaListView, ActualizacionCreateView, report, ActualizacionDetailView

app_name = 'historias_clinicas'

urlpatterns = [
    re_path(r'^historia-clinica$', HistoriaClinicaListView.as_view(), name='listar_historias'),
    re_path(r'^historia-clinica/(?P<pk>\d+)$', historia_paciente, name='historia_paciente'),
    re_path(r'^historia-clinica/(?P<pk>[0-9]+)/(?P<pk_A>[0-9]+)$',ActualizacionDetailView.as_view(), name='detalle_actualizacion'),
    re_path(r'^historia-clinica/(?P<pk>[0-9]+)/(?P<pk_A>[0-9]+)/pdf$',report, name='reporte_pdf'),
    re_path(r'^historia-clinica/(?P<pk>[0-9]+)/nueva-entrada$',
        ActualizacionCreateView.as_view(), name='crear_actualizacion'),
]

usuarios/urls.py
#from django.conf.urls import url
from django.urls import re_path
from . import views

app_name = 'usuarios'
urlpatterns = [
    re_path(r'^$', views.autenticar, name = 'autenticar'),
    re_path(r'^logout$', views.desautenticar, name = 'desautenticar'),
    re_path(r'^inicio$', views.inicio, name = 'inicio'),
]

historiasClinicas/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from pacientes.models import Paciente
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone

# Create your models here.


class Cabecera(models.Model):

    numero_historia = models.CharField(primary_key=True, max_length=15)
    paciente = models.OneToOneField(
        Paciente,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.numero_historia

class Actualizacion(models.Model):

    seleccion = (
        ('si','Si'),
        ('no','No')        
    )

    tipo_examen = (
        ('Pre-ingreso','Pre-ingreso'),
        ('Periodico','Periodico'),
        ('Egreso','Egreso'),
        ('Cambio labor','Cambio labor'),
        ('Reincorporacion laboral','Reincorporacion laboral'),
        ('Rev. Paraclinicos','Rev. Paraclinicos'),
        ('Manipulacion de alimentos','Manipulacion de alimentos'),
    )

    conceptos_valoracion_medica = (
        ('Apto para desempeñar cargo, sin patologia aparente','Apto para desempeñar el cargo sin patologia aparente'),
        ('Apto para cargo, con patologia que no limita labor','Apto para desempañar el cargo con patologia que no limita la labor'),
        ('Apto con restricciones o adaptaciones para labor','Apto con restricciones o adaptaciones para la labor'),
        ('Aplazado','Aplazado'),
        ('Apto para labor el alturas','Apto para labor el alturas'),
        ('Apto para continuar desempeñando su labor','Apto para continuar desempeñando su labor'),
        ('Examen de retiro','Examen de retiro'),
        ('Apto para manipulación de alimentos','Apto para manipulación de alimentos'),
    )

    restr_laborales = (
        ('no se encuentra','No se encuentra'),
        ('transitorias','Transitorias'),
        ('tiempo','Tiempo'),
        ('permanentes','Permanentes'),
    )

    remitenicia = (
        ('ninguno', 'Ninguno'),
        ('se remite EPS','Se remite a EPS'),
        ('continuar manejo medico EPS','Continuar manejo medico por EPS'),
        ('se remite ARL','Se remite a ARL'),
    )
    
    opciones_sistema_epidemiologico_ocupacional = (
        ('ergonomico','Ergonómico'),
        ('Psicosocial','Psicosocial'),
        ('auditivo','Autitivo'),
        ('visual','Visual'),
        ('respiratorio','Respitatorio'),
        ('biologico','Biológico'),
        ('quimico','Quimico'),
        ('accidente trabajo','Accidente de trabajo'),
        ('otro','Otro'),
        ('ninguno','Ninguno'),
    )
    fecha_actualizacion = models.DateField(auto_now=True)
    #motivo_consulta = models.TextField(default=None)
    #tratamiento = models.TextField(default=None)
    cabecera = models.ForeignKey(
        Cabecera,
        on_delete=models.CASCADE,
    )
    
    #Nuevos
    empresa = models.CharField(max_length=100)
    cargo_aspirado = models.CharField(max_length=150)
    eps = models.CharField(max_length=100, verbose_name='EPS')
    arl = models.CharField(max_length=100, verbose_name='ARL')
    examen_actual = models.CharField(max_length=50, choices=tipo_examen, verbose_name='Examen')
    #preingreso = models.CharField(max_length=1, default='')
    #periodico=models.CharField(max_length=1, default='')
    #egreso=models.CharField(max_length=1,  default='')
    #cambio_labor=models.CharField(max_length=1, default='')
    #reincorp_labor=models.CharField(max_length=1, default='')
    #rev_paraclinicos=models.CharField(max_length=1, default='')
    
    #   Antecedentes
    antecedentes_personales=models.TextField()
    antecedentes_laborales=models.TextField()
    antecedentes_familiares=models.TextField()
    antecedentes_ginecobstetricos=models.TextField()

    #   Examen Fisico
    ta=models.CharField(max_length=9, verbose_name='TA')
    fc=models.IntegerField(verbose_name='FC')
    fr=models.IntegerField(verbose_name='FR')
    peso=models.DecimalField(max_digits=5,decimal_places=2)
    talla=models.DecimalField(max_digits=5,decimal_places=2)
    imc=models.DecimalField(max_digits=60,decimal_places=2,verbose_name='IMC')
    cabeza_y_cuello=models.CharField(max_length=500)
    sentidos=models.CharField(max_length=500)
    cardiopulmonar=models.CharField(max_length=500)
    abdomen=models.CharField(max_length=500)
    osteomuscular=models.CharField(max_length=500)
    neurologico=models.CharField(max_length=500)
    esfera_mental=models.CharField(max_length=500)

    #   Concepto de valoracion medica
    valoracion_medica= models.CharField(
        max_length=100,
        choices=conceptos_valoracion_medica,
        verbose_name='Concepto de valoracion medica',
    )
    #apto_sin_pato=models.CharField(max_length=2)
    #apto_con_pato=models.CharField(max_length=2)
    #apto_con_restri=models.CharField(max_length=2)
    #aplazado=models.CharField(max_length=2)
    #apto_alturas=models.CharField(max_length=2)
    #apto_continuar_labor=models.CharField(max_length=2)
    #examen_retiro=models.CharField(max_length=2)
    #apto_alturas=models.CharField(max_length=2 )
    secuela_acci_trab=models.CharField(
        max_length=2, 
        choices=seleccion, 
        verbose_name='Secuela accidente de trabajo'
    )
    enfer_pro=models.CharField(
        max_length=2, 
        choices=seleccion, 
        verbose_name='Enfermedad profesional'
    )
    enfer_rel_trabajo=models.CharField(
        max_length=2, 
        choices=seleccion, 
        verbose_name='Enfermedad relacionada con el trabajo'
    )

    #reemplazar textfield por datepicker con bootstrap
    fecha_dxco = models.DateField(blank=True,null=True, verbose_name='Fecha del diagnostico')
    fecha_at = models.DateField(blank=True,null=True, verbose_name='Fecha accidente de trabajo')

    #   Resultados de laboratorios
    resultados_laboratorio=models.TextField(verbose_name='Resultados de laboratorio')
   
    #   Recomendaciones
    #Restricciones laborales
    restricciones_laborales = models.CharField(max_length=50, choices=restr_laborales)

    #Recomendaciones trabajador
    remite = models.CharField(max_length=50, choices=remitenicia, verbose_name='Se remite a')
    #no_encuentra=models.CharField(max_length=2)
    #transitorias=models.CharField(max_length=2)
    #tiempo=models.CharField(max_length=10)
    #permanentes=models.CharField(max_length=2)
    #remite_eps=models.CharField(max_length=2)
    #continuar_eps=models.CharField(max_length=2)
    #remite_arl=models.CharField(max_length=2)

    #recomendaciones empresa
    otras=models.TextField(verbose_name='Recomendaciones para la empresa')
    observaciones=models.TextField(verbose_name='Observaciones')

    ingreso_sis_epidem_ocup = models.CharField(
        max_length=50, 
        choices=opciones_sistema_epidemiologico_ocupacional, 
        verbose_name='Ingresar al trabajador examinado al Sistema de Vigilancia Epidemiológica Ocupacional'
    )
    #auditivo=models.CharField(max_length=2)
    #visual=models.CharField(max_length=2)
    #respiratorio=models.CharField(max_length=2)
    #biologico=models.CharField(max_length=2)
    #quimico=models.CharField(max_length=2)
    #ergonomico=models.CharField(max_length=2)
    #psicosocial=models.CharField(max_length=2)
    #accidente_trabajo=models.CharField(max_length=2)
    #otro=models.CharField(max_length=2)
    #ninguno=models.CharField(max_length=2)

    def __str__(self):
        return str(self.id)

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('historias_clinicas:historia_paciente', kwargs={'pk': self.cabecera.numero_historia})


@receiver(post_save, sender=Paciente)
def crearCabecera(sender, **kwargs):
    cabecera_usuario = Cabecera.objects.create(
        numero_historia=kwargs['instance'].cedula, paciente=kwargs['instance'])
    cabecera_usuario.save()

templates/historiasClinicas/actualizacion_detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block style_content %}
    <link rel="stylesheet" href="{% static 'css/historiaClinica.css' %}">
{% endblock style_content %}

{% block content %}
<section id="section-container">
        <div class="container-fluid">
            <div class="row ml-2 mr-2 fila">
                <div class="col-12 col-md-6 col-lg-4">
                    <h5>Paciente:</h6>
                    <p>{{ paciente.primer_nombre }} {{ paciente.segundo_nombre }} {{ paciente.primer_apellido }} {{ paciente.segundo_apellido }}</p>
                </div>
                <div class="col-12 col-md-6 col-lg-4">
                    <h5>Cedula:</h6>
                    <p>{{ paciente.cedula }}</p>
                </div>
                <div class="col-12 col-md-6 col-lg-4">
                    <h5>Fecha de nacimiento: </h6>
                    <p>{{ paciente.fecha_nacimiento }}</p>
                </div>
                <div class="col-12 col-md-6 col-lg-4">
                    <h5>Direccion: </h6>
                    <p>{{ paciente.direccion }}</p>
                </div>
                <div class="col-12 col-md-6 col-lg-4">
                    <h5>Ciudad: </h6>
                        <p>{{ paciente.ciudad }}</p>
                </div>
                <div class="col-12 col-md-6 col-lg-4">
                    <h5>Telefono: </h6>
                        <p>{{ paciente.telefono }}</p>
                </div>
            </div>
        </div>
    </section>
    <section id="section-container">
        <div class="container-fluid">
            <div class="row fila ml-2 mr-2 p-3 justify-content-around">
                <div class="col-12 text-center mb-4 mt-2">
                    <h4>
                        Fecha de actualizacion: {{actualizacion.fecha_actualizacion}}
                    </h4>
                </div>
                <div class="border border-secondary rounded col-12 col-md-6 col-lg-4 mb-3">
                    <h4 class="mb-3 mt-2 text-center font-weight-bold">Identificacion</h4>
                    <h5>Empresa</h5>
                    <p class="ml-2 mb-4">{{actualizacion.empresa}}</p>
                    <h5>Cargo aspirado</h5>
                    <p class="ml-2 mb-4">{{actualizacion.cargo_aspirado}}</p>
                    <h5>EPS</h5>
                    <p class="ml-2 mb-4">{{actualizacion.eps}}</p>
                    <h5>ARL</h5>
                    <p class="ml-2 mb-4">{{actualizacion.arl}}</p>
                    <h5>Examen</h5>
                    <p class="ml-2 mb-4">{{actualizacion.get_examen_actual_display}}</p>
                </div>
                <div class="border border-secondary rounded col-12 col-md-6 col-lg-7 mb-3">
                    <h4 class="mb-3 mt-2 text-center font-weight-bold">Antecedentes</h4>
                    <h5>Antecedentes personales</h5>
                    <p class="ml-2 mb-4 text-justify">{{actualizacion.antecedentes_personales}}</p>
                    <h5>Antecedentes familiares</h5>
                    <p class="ml-2 mb-4 text-justify">{{actualizacion.antecedentes_familiares}}</p>
                    <h5>Antecedentes laborales</h5>
                    <p class="ml-2 mb-4 text-justify">{{actualizacion.antecedentes_laborales}}</p>
                    <h5>Antecedentes ginecobstetricos</h5>
                    <p class="ml-2 mb-4 text-justify">{{actualizacion.antecedentes_ginecobstetricos}}</p>
                </div>
                <div class="border border-secondary rounded col-12 col-lg-5 mb-3 mt-2">
                        <h4 class="mb-3 mt-2 text-center font-weight-bold">Examen Físico</h4>
                        <div class="row">
                            <div class="col-12 col-lg-6 mt-2">
                                    <h5>Tension Arterial</h5>
                                    <p class="ml-2 mb-4 text-justify">{{actualizacion.ta}}</p>
                                    <h5>Frecuencia Cardiaca</h5>
                                    <p class="ml-2 mb-4 text-justify">{{actualizacion.fc}}</p>
                                    <h5>Frecuencia Respiratoria</h5>
                                    <p class="ml-2 mb-4 text-justify">{{actualizacion.fr}}</p>
                                    <h5>Peso</h5>
                                    <p class="ml-2 mb-4 text-justify">{{actualizacion.peso}}</p>
                                    <h5>Talla</h5>
                                    <p class="ml-2 mb-4 text-justify">{{actualizacion.talla}}</p>
                                    <h5>IMC</h5>
                                    <p class="ml-2 mb-4 text-justify">{{actualizacion.imc}}</p>
                            </div>
                            <div class="col-12 col-lg-6 mt-2">
                                    <h5>Cabeza Y Cuello</h5>
                                    <p class="ml-2 mb-4 text-justify">{{actualizacion.cabeza_y_cuello}}</p>
                                    <h5>Sentidos</h5>
                                    <p class="ml-2 mb-4 text-justify">{{actualizacion.sentidos}}</p>
                                    <h5>Cardiopulmonar</h5>
                                    <p class="ml-2 mb-4 text-justify">{{actualizacion.cardiopulmonar}}</p>
                                    <h5>Abdomen</h5>
                                    <p class="ml-2 mb-4 text-justify">{{actualizacion.abdomen}}</p>
                                    <h5>Osteomuscular</h5>
                                    <p class="ml-2 mb-4 text-justify">{{actualizacion.osteomuscular}}</p>
                                    <h5>Neurologico</h5>
                                    <p class="ml-2 mb-4 text-justify">{{actualizacion.neurologico}}</p>
                                    <h5>Esfera mental</h5>
                                    <p class="ml-2 mb-4 text-justify">{{actualizacion.esfera_mental}}</p>
                            </div>
                        </div>     
                </div>
                <div class="border border-secondary rounded col-12 col-lg-6 mb-3 mt-2">
                        <h4 class="mb-3 mt-2 text-center font-weight-bold">Concepto de valoración médica</h4>
                        <h5>valoración médica</h5>
                        <p class="ml-2 mb-4 text-justify">{{actualizacion.valoracion_medica}}</p>
                        <h5>Secuela de accidente de trabajo</h5>
                        <p class="ml-2 mb-4 text-justify">{{actualizacion.secuela_acci_trab}}</p>
                        <h5>Enfermedad profesional</h5>
                        <p class="ml-2 mb-4 text-justify">{{actualizacion.enfer_pro}}</p>
                        <h5>Enfermedad relacionada con el trabajo</h5>
                        <p class="ml-2 mb-4 text-justify">{{actualizacion.enfer_rel_trabajo}}</p>
                        <h5>Fecha del diferencial</h5>
                        <p class="ml-2 mb-4 text-justify">{{actualizacion.fecha_dxco}}</p>
                        <h5>Fecha del accidente de trabajo</h5>
                        <p class="ml-2 mb-4 text-justify">{{actualizacion.fecha_at}}</p>
                </div>
                <div class="border border-secondary rounded col-11 mt-2 mb-3">
                        <h4 class="mb-3 mt-2 text-center font-weight-bold">Resultados de laboratorio</h4>
                        <p class="ml-2 mb-4 text-justify">{{actualizacion.resultados_laboratorio}}</p>
                </div>
                <div class="border border-secondary rounded col-11 mb-3 mt-2">
                        <h4 class="mb-3 mt-2 text-center font-weight-bold">Recomendaciones para el trabajador</h4>
                        <h5>Restricciones laborales</h5>
                        <p class="ml-2 mb-4 text-justify">{{actualizacion.restricciones_laborales}}</p>
                        <h5>Remite a</h5>
                        <p class="ml-2 mb-4 text-justify">{{actualizacion.get_remite_display}}</p>
                        <h4 class="mb-3 mt-2 text-center font-weight-bold">Recomendaciones para la empresa</h4>
                        <h5>Otras</h5>
                        <p class="ml-2 mb-4 text-justify">{{actualizacion.otras}}</p>
                        <h5>Ingresar al examinado al Sistema de Vigilancia Epidemiologica Ocupacional</h5>
                        <p class="ml-2 mb-4 text-justify">{{actualizacion.ingreso_sis_epidem_ocup}}</p>
                </div>
                <div class="border border-secondary rounded col-11 mt-2 mb-3">
                    <h4 class="mb-3 mt-2 text-center font-weight-bold">Observaciones</h4>
                    <p class="ml-2 mb-4 text-justify">{{actualizacion.observaciones}}</p>
                </div>
                <a href="{% url 'historias_clinicas:reporte_pdf' pk=paciente.cedula pk_A=actualizacion.id %}" class="btn btn-outline-primary btn-block"> Generar PDF </a>
            </div>
        </div>
    </section>
{% endblock content %}

templates/historiasClinicas/actualizacion_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load staticfiles %}

{% block style_content %}
    <link rel="stylesheet" href=" {% static 'css/ActualizacionRegistro.css' %}"> 
{% endblock style_content %}


{% block content %}
<section id="section-container">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-md-8 col-lg-8 column">
                <h2 class="text-center">Nueva entrada historia clinica</h2>
            </div>
        </div>
</section>
<section id="section-container">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-md-8 col-lg-8 column">
                <form method="POST">
                    {% csrf_token %} 
                    {% for hidden in form.hidden_fields%} 
                        {{hidden}} 
                    {% endfor %} 
                    
                    {% for field in form.visible_fields %}
                    {% if field.name == 'empresa'%}
                    <h4 class="subtitulo">Identificacion</h4>
                    {% endif %}
                    {% if field.name == 'antecedentes_personales'%}
                    <h4 class="subtitulo">Antecedentes</h4>
                    {% endif %}
                    {% if field.name == 'ta'%}
                    <h4 class="subtitulo">Examen Físico</h4>
                    {% endif %}
                    {% if field.name == 'valoracion_medica'%}
                    <h4 class="subtitulo">Valoracion Medica</h4>
                    {% endif %}
                    {% if field.name == 'resultados_laboratorio'%}
                    <h4 class="subtitulo">Resultados de Laboratorio</h4>
                    {% endif %}
                    {% if field.name == 'restricciones_laborales'%}
                    <h4 class="subtitulo">Recomendaciones para el trabajador</h4>
                    {% endif %}
                    {% if field.name == 'otras'%}
                    <h4 class="subtitulo">Recomendaciones para la empresa</h4>
                    {% endif %}
                    {% if field.name == 'observaciones'%}
                    <h4 class="subtitulo">Observaciones</h4>
                    {% endif %}
                    <div class="form-group">
                        <label for="{{field.id_for_label}}">{{field.label}}</label> 
                        {{ field|add_class:'form-control' }}
                        {% if field.name == 'fecha_dxco' or field.name == 'fecha_at' %}
                        <small id="date-help" class="form-text text-muted">Porfavor use el siguente formato 'YYYY-MM-DD'</small>
                        {% endif %}         
                    </div>
                    {% endfor %}
                    <input type="submit" class="btn btn-outline-primary btn-block">
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

{% block scripts %}
<script src="{% static 'js/calcularIMC.js' %}"></script>
{% endblock scripts %}

templates/historiasClinicas/cabecera_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block style_content %}
    <link rel="stylesheet" href="{% static 'css/PacientesLista.css' %}">
    <link rel="stylesheet" href="{% static 'css/PacienteRegistro.css' %}"> 
{% endblock style_content %} 

{% block content %}
<section id="section-container">
    <div class="container">
        <div class="row fila">
            <div class="col-12 text-center pt-3 pb-2">
                <h2>Lista de historias clinicas</h2>
            </div>
        </div>
        <div class="row fila">
            <div class="col-12">
                <div class="list-group">
                    {% for cabecera in object_list%}
                    <a href="{% url 'historias_clinicas:historia_paciente' pk=cabecera.numero_historia %}" class="list-group-item list-group-item-action flex-column">
                        <div class="d-flex w-100 text-center">
                            <h5 class="mb-1">Historia clinica #{{ cabecera.numero_historia }}</h5>
                        </div>
                    </a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

templates/historiasClinicas/historia_clinica.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block style_content %}
    <link rel="stylesheet" href="{% static 'css/historiaClinica.css' %}">
{% endblock style_content %}
    

{% block content %}
    <section id="section-container">
        <div class="container-fluid">
            <div class="row ml-2 mr-2 fila">
                <div class="col-12 column text-center">
                    <h2>Historia Clinica #{{ cabecera.numero_historia }}</h2>
                </div>
            </div>
        </div>
    </section>
    <section id="section-container">
        <div class="container-fluid">
            <div class="row ml-2 mr-2 fila">
                <div class="col-12 col-md-6 col-lg-4">
                    <h5>Paciente:</h6>
                    <p>{{ paciente.primer_nombre }} {{ paciente.segundo_nombre }} {{ paciente.primer_apellido }} {{ paciente.segundo_apellido }}</p>
                </div>
                <div class="col-12 col-md-6 col-lg-4">
                    <h5>Cedula:</h6>
                    <p>{{ paciente.cedula }}</p>
                </div>
                <div class="col-12 col-md-6 col-lg-4">
                    <h5>Fecha de nacimiento: </h6>
                    <p>{{ paciente.fecha_nacimiento }}</p>
                </div>
                <div class="col-12 col-md-6 col-lg-4">
                    <h5>Direccion: </h6>
                    <p>{{ paciente.direccion }}</p>
                </div>
                <div class="col-12 col-md-6 col-lg-4">
                    <h5>Ciudad: </h6>
                        <p>{{ paciente.ciudad }}</p>
                </div>
                <div class="col-12 col-md-6 col-lg-4">
                    <h5>Telefono: </h6>
                        <p>{{ paciente.telefono }}</p>
                </div>
                <div class="col-12">
                    <a href="{% url 'historias_clinicas:crear_actualizacion' pk=paciente.cedula %}" class="btn btn-outline-primary btn-block"> Ingresar nueva entrada </a>
                </div>
            </div>
        </div>
    </section>
    <section id="section-container">
        <div class="container">
            <div class="row fila">
                <div class="col-12">
                    <div class="list-group">
                        {% for actualizacion in actualizaciones %}
                        <a href="{% url 'historias_clinicas:detalle_actualizacion' pk=paciente.cedula pk_A=actualizacion.pk %}" class="list-group-item list-group-item-action flex-column">
                            <div class="d-flex w-100 justify-content-center">
                            <h5 class="mb-1 text-center">Fecha de la consulta: {{actualizacion.fecha_actualizacion}}</h5>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% endfor %}
{% endblock content %}
    